[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix server", "npm install --prefix client"]

[phases.build]
cmds = ["npm run build --prefix client", "node scripts/copy-client.js"]

[start]
cmd = "npm --prefix server start"
